- id: '1775035001609'
  alias: CPU Fan
  description: ''
  triggers:
    - trigger: homeassistant
      event: start
    - trigger: time_pattern
      seconds: /30
  conditions: []
  actions:
    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.cpu_temperature
              above: 35
          sequence:
            - action: switch.turn_on
              target:
                entity_id: switch.rpi_cooling_fan
        - conditions:
            - condition: numeric_state
              entity_id: sensor.cpu_temperature
              below: 25
          sequence:
            - action: switch.turn_off
              target:
                entity_id: switch.rpi_cooling_fan