- id: '1775401399136'
  alias: HA Boot - Notify Discord
  description: ''
  triggers:
    - trigger: homeassistant
      event: start
  conditions: [ ]
  actions:
    - action: script.ha_online_notify_discord
      metadata: { }
      data: { }
  mode: single
- id: '1776016632067'
  alias: Toggle Bedroom Light
  description: Toggle Bedroom Light
  triggers:
    - event_type: ios.action_fired
      event_data:
        actionName: Bedroom Light
      trigger: event
  actions:
    - action: light.toggle
      target:
        entity_id:
          - light.lamp
      data: { }
  initial_state: true
- id: '1776017712312'
  alias: Shutters - Automate close
  description: ''
  triggers:
    - device_id: ad05755c837a93408b2addf5f3428bd5
      domain: device_tracker
      entity_id: 23e9209e33aa806eace56679123e2064
      type: leaves
      trigger: device
      zone: zone.goor
      alias: Trigger when Michiel leaves Goor
    - trigger: sun
      event: sunset
      offset: 00:30:00
      alias: Trigger 30 minutes after sunset
    - trigger: time
      at: 00:00:00
      alias: Trigger at midnight
  actions:
    - parallel:
        - if:
            - condition: numeric_state
              entity_id: cover.shutter_back
              attribute: current_position
              above: 10
          then:
            - device_id: 87fec662ee8dd99a998779420a0df21f
              domain: cover
              entity_id: ab8adbecf1dbd16bed4c55fdab901524
              type: set_position
              position: 10
          alias: Close back shutter if it is not closed
        - if:
            - condition: numeric_state
              entity_id: cover.shutter_front
              attribute: current_position
              above: 10
          then:
            - device_id: a04597364adc21334952e4e620432ac3
              domain: cover
              entity_id: a06305603ccf50171c809860db3fd263
              type: set_position
              position: 10
          alias: Close front shutter if it is not closed
      alias: Close both shutters in parallel
  mode: single
- id: '1776018353672'
  alias: Shutters - Automate open
  description: ''
  triggers:
    - device_id: ad05755c837a93408b2addf5f3428bd5
      domain: device_tracker
      entity_id: 23e9209e33aa806eace56679123e2064
      type: enters
      trigger: device
      zone: zone.home
      alias: Trigger when Michiel comes home
    - trigger: sun
      event: sunrise
      offset: 00:30
      alias: Trigger 30 minutes after sunrise
    - trigger: time_pattern
      hours: '8'
      minutes: /10
      alias: Trigger every 10 minutes from 8:00 until 9:00
  conditions:
    - condition: and
      conditions:
        - condition: numeric_state
          entity_id: weather.buienradar
          attribute: temperature
          above: 5
          below: 25
        - condition: device
          device_id: ad05755c837a93408b2addf5f3428bd5
          domain: device_tracker
          entity_id: 23e9209e33aa806eace56679123e2064
          type: is_home
        - condition: sun
          before: sunset
  actions:
    - alias: Open both shutters in parallel
      parallel:
        - alias: Open back shutter if it is not open
          if:
            - condition: numeric_state
              entity_id: cover.shutter_back
              attribute: current_position
              below: 40
          then:
            - device_id: 87fec662ee8dd99a998779420a0df21f
              domain: cover
              entity_id: ab8adbecf1dbd16bed4c55fdab901524
              type: set_position
              position: 75
        - alias: Open front shutter if it is not open
          if:
            - condition: numeric_state
              entity_id: cover.shutter_front
              attribute: current_position
              below: 40
          then:
            - device_id: a04597364adc21334952e4e620432ac3
              domain: cover
              entity_id: a06305603ccf50171c809860db3fd263
              type: set_position
              position: 75
  mode: single
- id: '1776018447752'
  alias: Light - Turn off front door light at sunrise
  description: ''
  triggers:
    - trigger: sun
      event: sunrise
      offset: 0
  conditions: [ ]
  actions:
    - type: turn_off
      device_id: 34c956818579dcd31256511c20a2d4cd
      entity_id: 0bce3f968431fd0d445527bda8ba69bb
      domain: switch
  mode: single
- id: '1776018485717'
  alias: Light - Turn on front door light at sunset
  description: ''
  triggers:
    - trigger: sun
      event: sunset
      offset: 0
  conditions: [ ]
  actions:
    - type: turn_on
      device_id: 34c956818579dcd31256511c20a2d4cd
      entity_id: 0bce3f968431fd0d445527bda8ba69bb
      domain: switch
  mode: single